name: "Сообщить о проблеме"
description: "Если что-то работает не так, как ожидалось."
labels: ["Bug"]
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Описание"
      description: "Опишите одну проблему как можно подробнее"

  - type: textarea
    id: should_happen
    attributes:
      label: "Что должно было произойти"
      description: "То, что вы ожидали"
      placeholder: |
        Открытое меню автолата не вызывает лаги

  - type: textarea
    id: happened
    attributes:
      label: "Что произошло на самом деле"
      description: "То, что случилось"
      placeholder: |
        Очень сильно лагает компьютер, когда я открываю автолат

  - type: textarea
    id: reproduction
    attributes:
      label: "Шаги воспроизведения"
      description: "Если приемлемо, опишите шаги для воспроизведения проблемы"
      placeholder: |
        1. Найти автолат
        2. Открыть его меню, кликнул ЛКМ
        3. Получить лаги

  - type: textarea
    id: additional
    attributes:
      label: "Дополнительная информация:"
      description: |
        Вы можете добавьте скриншоты, чтобы помочь описать вашу проблему
        **Подсказка**: Вы можете прикрепить изображения, щелкнув по области ниже для её выделения,
         а затем перетащите в неё файлы
